import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Press_Start_2P, Pixelify_Sans } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  weight: '400',
});

const pixelFont = Press_Start_2P({
  subsets: ['latin'],
  weight: '400',
});

const pixelify = Pixelify_Sans({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixelify.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
