import type { Metadata } from "next";
import { Pixelify_Sans } from 'next/font/google';
import { PhotoProvider } from '@/context/PhotoContext'
import "./globals.css";

const pixelify = Pixelify_Sans({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pixelify.className} antialiased`}>
         <PhotoProvider>
          {children}
         </PhotoProvider>
      </body>
    </html>
  );
}
